name: Mabinogi Notice Bot

on:
  schedule:
    - cron: "*/60 * * * *" # 60분마다 체크
  workflow_dispatch: # 수동 실행 옵션

jobs:
  check-notices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add previous_notices.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update previous notices" && git push)
